name: lead_your_way
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.4.5
  fluttertoast: ^8.2.2
  formz: ^0.6.1
  google_nav_bar: ^5.0.6
  lottie: ^2.6.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  state_notifier: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo-lyw.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
